# Form implementation generated from reading ui file 'final_qt.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 232)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(20, 120, 75, 24))
        self.ok.setObjectName("ok")
        self.weburl = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.weburl.setGeometry(QtCore.QRect(10, 80, 251, 22))
        self.weburl.setObjectName("weburl")
        self.isvestis = QtWidgets.QLabel(parent=self.centralwidget)
        self.isvestis.setGeometry(QtCore.QRect(290, 50, 341, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setKerning(False)
        self.isvestis.setFont(font)
        self.isvestis.setText("")
        self.isvestis.setWordWrap(True)
        self.isvestis.setObjectName("isvestis")
        self.enter = QtWidgets.QLabel(parent=self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(21, 50, 261, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setKerning(False)
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ok.setText(_translate("MainWindow", "OK"))
        self.enter.setText(_translate("MainWindow", "Iveskite svetaine "))
